{
    'name': 'Integrated IVCS',
    'version': '1.0',
    'category': 'Development',
    'summary': 'Integrated Version Control System with Git and Nostr',
    'author': 'Your Name',
    'website': 'https://www.example.com',
    'depends': ['base', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/ivcs_item_views.xml',
        'views/ivcs_version_views.xml',
        'views/ivcs_commit_views.xml',
        'views/git_repository_views.xml',
        'views/nostr_event_views.xml',
        'views/res_config_settings_views.xml',
        'wizards/create_branch_wizard_views.xml',
        'wizards/create_commit_wizard_views.xml',
    ],
    'external_dependencies': {
        'python': ['git', 'nostr'],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
