{
    'name': 'Integrated Version Control System with Git',
    'version': '1.1',
    'category': 'Tools',
    'summary': 'Git-based version control system integrated with Odoo',
    'depends': ['base', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'wizards/create_version_wizard_view.xml',
        'wizards/add_remote_wizard_view.xml',
        'wizards/create_file_wizard_view.xml',
        'wizards/create_branch_wizard_view.xml',
        'wizards/switch_branch_wizard_view.xml',
        'wizards/merge_branches_wizard_view.xml',
        'wizards/rebase_branch_wizard_view.xml',
        'views/ivcs_wizard_actions.xml',
        'views/ivcs_item_views.xml',
        'views/ivcs_version_views.xml',
        'views/ivcs_workflow_views.xml',
        'views/res_config_settings_views.xml',
        'views/ivcs_commit_views.xml',
        'data/ir_cron_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
